# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46bb50c6fd686b7b915f56f5844c825e4cca71f4d147c49a498c736837262da28e090ebc0aecd7c79c9822edddfbbd1399fe6b9b8c5217c2cb369ca4ff8ea233

test:
  secret_key_base: 32775d265b21de2e293d4b34cadefe3f04da83c4416585867f32e1c7cfd7b99f3931fcc0c928a739bf7e3645562faa774418045bcb4f6b950b78fee6fa358c56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
